server:
  port: 8080
spring:
  application:
    name: 'customer-service'

  cloud:
    config:
      enabled: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/customerdb

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0 # Captura 100% das requisições (ajuste em produção)
  metrics:
    export:
      prometheus:
        enabled: true

# OpenTelemetry export para o Collector
otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  resource:
    attributes:
      service.name: customer-service